name: R

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.1"
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
        packages: |
          any::tidyverse 
          any::googlesheets4
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
